[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm install --no-package-lock && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
